# Generated by Django 3.2.4 on 2021-06-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_auto_20210614_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, default='lambda:choice(descriptions_list)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='lambda:choice(locations_list)', max_length=30),
        ),
    ]
