# Generated by Django 3.2.4 on 2021-06-20 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_alter_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_blank',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_messages', to='chat_app.room'),
        ),
    ]
