# Generated by Django 3.2.4 on 2021-06-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0008_auto_20210621_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_common',
            field=models.BooleanField(default=False),
        ),
    ]
