# Generated by Django 3.2.4 on 2021-06-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0008_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='organizer',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
